{
 "title": "TNOM",
 "description": "TNOM is a monitoring tool for checking Nibiru price feeder if it is signing all the necessary Nibiru Oracle price updates",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job_name",
    "label": "job name",
    "query": {
     "query": "label_values({instance=\"localhost:7130\"},job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Price feeder wallet balance",
   "type": "gauge",
   "description": "Wallet balance of the price feeder",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tnom_price_feed_balance{job=\"$job_name\"} / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "description": "Showing current epoch",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tnom_slash_epoch{job=\"$job_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unsigned Events",
   "type": "gauge",
   "description": "It shows the amount of times price feeder didn't sign oracle price update transactions",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tnom_unsigned_oracle_events{job=\"$job_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Miss events",
   "type": "gauge",
   "description": "This gague differs from unsigned events. It is for monitroing if price feed missed price point. ",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tnom_miss_counter_events{job=\"$job_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "No APIs working",
     "type": "gauge",
     "description": "No APIs working for X amount of checks",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tnom_api_cons_miss{job=\"$job_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Executed P1 Alert for miss counter",
     "type": "stat",
     "description": "True if executed false if not executed",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bool" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tnom_miss_counter_events_p1_executed{job=\"$job_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Executed P2 Alert for miss counter",
     "type": "stat",
     "description": "True if executed false if not executed",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bool" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tnom_miss_counter_events_p2_executed{job=\"$job_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Executed P3 Alert for miss counter",
     "type": "stat",
     "description": "True if executed false if not executed",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bool" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tnom_miss_counter_events_p3_executed{job=\"$job_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Executed very small balance alert",
     "type": "stat",
     "description": "True if executed false if not executed",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bool" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tnom_very_small_balance_alert_executed{job=\"$job_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Executed Small balance Alert ",
     "type": "stat",
     "description": "True if executed false if not executed",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bool" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tnom_small_balance_alert_executed{job=\"$job_name\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}